# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.75

## Mod Properties
mod_id=astral_craft
mod_name=Astral Craft
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.astral_craft